using FixFinder.Core.Engine;
using FixFinder.Core.Execution;
using FixFinder.Core.Http;
using FixFinder.Core.LocalFixes;
using FixFinder.Core.Sources;

namespace FixFinder.Tests;

/// <summary>
/// The mistakes of a computer science degree past the first weeks - data structures and algorithms, systems programming in C,
/// operating systems and concurrency, networks, databases, web and async code - each run through FixFinder for real, and fixed.
/// </summary>
/// <remarks>
/// Live. Each case skips when its toolchain is missing, and a skip looks like a pass. Freshly built C and C++ programs can be
/// refused by Application Control on a machine enforcing it, which fails the case for a reason that is not the rule's.
/// </remarks>
public class CourseworkTests
{
    /// <summary>The toolchain, the program, its files, the one run, what is typed in, the answer's id, and text the copied fix must contain.</summary>
    public static TheoryData<string, string, Dictionary<string, string>, string, string?, string, string> Programs => new()
    {
        { "python", "y1-json-loads-file", new() { ["app.py"] = "import json\n\nwith open(\"scores.json\", \"w\") as f:\n    json.dump({\"ada\": 90}, f)\n\nwith open(\"scores.json\") as f:\n    scores = json.loads(f)\n\nprint(scores[\"ada\"])\n" }, "app.py", null, "local:python-json-load-loads", "scores = json.load(f)" },
        { "python", "y1-range-of-input", new() { ["app.py"] = "n = input(\"How many? \")\nfor i in range(n):\n    print(i)\n" }, "app.py", "3\n", "local:python-input-not-number", "n = int(input(\"How many? \"))" },
        { "python", "y2-abstract-method-unwritten", new() { ["app.py"] = "from abc import ABC, abstractmethod\n\n\nclass Shape(ABC):\n    @abstractmethod\n    def area(self):\n        pass\n\n\nclass Square(Shape):\n    def __init__(self, side):\n        self.side = side\n\n\nprint(Square(3).area())\n" }, "app.py", null, "local:python-unwritten-abstract-method", "raise NotImplementedError(\"area is not written yet\")" },
        { "python", "y2-dataclass-mutable-default", new() { ["app.py"] = "from dataclasses import dataclass\n\n\n@dataclass\nclass Stack:\n    items: list = []\n\n    def push(self, item):\n        self.items.append(item)\n\n\ns = Stack()\ns.push(1)\nprint(s.items)\n" }, "app.py", null, "local:python-dataclass-default-factory", "items: list = field(default_factory=list)" },
        { "python", "y2-deque-pop-zero", new() { ["app.py"] = "from collections import deque\n\ngraph = {\"a\": [\"b\", \"c\"], \"b\": [\"d\"], \"c\": [], \"d\": []}\n\n\ndef bfs(start):\n    queue = deque([start])\n    seen = {start}\n    order = []\n    while queue:\n        node = queue.pop(0)\n        order.append(node)\n        for nxt in graph[node]:\n            if nxt not in seen:\n                seen.add(nxt)\n                queue.append(nxt)\n    return order\n\n\nprint(bfs(\"a\"))\n" }, "app.py", null, "local:python-deque-popleft", "node = queue.popleft()" },
        { "python", "y2-eq-without-hash", new() { ["app.py"] = "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __eq__(self, other):\n        return (self.x, self.y) == (other.x, other.y)\n\n\nseen = {Point(1, 2)}\nprint(Point(1, 2) in seen)\n" }, "app.py", null, "local:python-hash-with-eq", "return hash((self.x, self.y))" },
        { "python", "y2-set-append", new() { ["app.py"] = "def dfs(graph, node, visited=None):\n    if visited is None:\n        visited = set()\n    visited.append(node)\n    for nxt in graph[node]:\n        if nxt not in visited:\n            dfs(graph, nxt, visited)\n    return visited\n\n\nprint(sorted(dfs({\"a\": [\"b\"], \"b\": [\"a\"]}, \"a\")))\n" }, "app.py", null, "local:python-set-method", "visited.add(node)" },
        { "python", "y2-sort-cmp", new() { ["app.py"] = "def by_length(a, b):\n    return len(a) - len(b)\n\n\nwords = [\"banana\", \"fig\", \"apple\"]\nwords.sort(cmp=by_length)\nprint(words)\n" }, "app.py", null, "local:python-sort-cmp", "words.sort(key=cmp_to_key(by_length))" },
        { "python", "y2-super-without-brackets", new() { ["app.py"] = "class Animal:\n    def __init__(self, name):\n        self.name = name\n\n\nclass Dog(Animal):\n    def __init__(self, name):\n        super.__init__(name)\n\n\nprint(Dog(\"Rex\").name)\n" }, "app.py", null, "local:python-super-call", "super().__init__(name)" },
        { "python", "y3-bytes-plus-str", new() { ["app.py"] = "import socket\n\na, b = socket.socketpair()\na.sendall(b\"hello\")\ndata = b.recv(1024)\nprint(\"received: \" + data)\n" }, "app.py", null, "local:python-str-concatenation", "print(\"received: \" + data.decode())" },
        { "python", "y3-hash-a-str", new() { ["app.py"] = "import hashlib\n\npassword = \"hunter2\"\ndigest = hashlib.sha256(password).hexdigest()\nprint(digest)\n" }, "app.py", null, "local:python-text-to-bytes", "hashlib.sha256(password.encode())" },
        { "python", "y3-json-dump-set", new() { ["app.py"] = "import json\n\ntags = {\"python\", \"sql\"}\nprint(json.dumps(tags))\n" }, "app.py", null, "local:python-json-set", "json.dumps(list(tags))" },
        { "python", "y3-process-without-main-guard", new() { ["app.py"] = "from multiprocessing import Process\n\n\ndef work(n):\n    print(\"working on\", n)\n\n\np = Process(target=work, args=(1,))\np.start()\np.join()\n" }, "app.py", null, "local:python-main-guard", "if __name__ == \"__main__\":" },
        { "python", "y3-socket-bind-two-arguments", new() { ["app.py"] = "import socket\n\nserver = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\nserver.bind(\"127.0.0.1\", 0)\nserver.listen()\nprint(\"listening on\", server.getsockname()[1])\nserver.close()\n" }, "app.py", null, "local:python-socket-address", "server.bind((\"127.0.0.1\", 0))" },
        { "python", "y3-socket-send-str", new() { ["app.py"] = "import socket\n\na, b = socket.socketpair()\na.sendall(\"hello\")\nprint(b.recv(1024))\n" }, "app.py", null, "local:python-text-to-bytes", "a.sendall(b\"hello\")" },
        { "python", "y3-sqlite-bindings", new() { ["app.py"] = "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\ncur = conn.cursor()\ncur.execute(\"CREATE TABLE users (name TEXT)\")\nname = \"ada\"\ncur.execute(\"INSERT INTO users VALUES (?)\", (name))\nconn.commit()\nprint(cur.execute(\"SELECT COUNT(*) FROM users\").fetchone()[0])\n" }, "app.py", null, "local:python-sql-parameter-tuple", "(name,))" },
        { "python", "y3-thread-args-not-tuple", new() { ["app.py"] = "import threading\n\n\ndef worker(n):\n    print(\"worker\", n)\n\n\nt = threading.Thread(target=worker, args=(5))\nt.start()\nt.join()\n" }, "app.py", null, "local:python-args-tuple", "args=(5,)" },
        { "python", "y4-coroutine-not-awaited", new() { ["app.py"] = "import asyncio\n\n\nasync def fetch(n):\n    await asyncio.sleep(0.01)\n    return n * 2\n\n\nasync def main():\n    result = fetch(21)\n    print(result + 1)\n\n\nasyncio.run(main())\n" }, "app.py", null, "local:python-coroutine-not-awaited", "result = await fetch(21)" },
        { "python", "y4-gather-a-list", new() { ["app.py"] = "import asyncio\n\n\nasync def fetch(n):\n    await asyncio.sleep(0.01)\n    return n * 2\n\n\nasync def main():\n    results = await asyncio.gather([fetch(1), fetch(2)])\n    print(results)\n\n\nasyncio.run(main())\n" }, "app.py", null, "local:python-gather-list", "asyncio.gather(fetch(1), fetch(2))" },
        { "python", "y4-generator-len", new() { ["app.py"] = "def evens(limit):\n    for n in range(limit):\n        if n % 2 == 0:\n            yield n\n\n\nprint(len(evens(10)))\n" }, "app.py", null, "local:python-generator-len", "len(list(evens(10)))" },
        { "python", "y4-match-positional-pattern", new() { ["app.py"] = "class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n\ndef describe(p):\n    match p:\n        case Point(0, 0):\n            return \"origin\"\n        case Point(x, y):\n            return f\"({x}, {y})\"\n\n\nprint(describe(Point(1, 2)))\n" }, "app.py", null, "local:python-match-args", "__match_args__ = (\"x\", \"y\")" },
        { "java", "y1-aslist-add", new() { ["App.java"] = "import java.util.Arrays;\nimport java.util.List;\n\npublic class App {\n    public static void main(String[] args) {\n        List<Integer> marks = Arrays.asList(70, 65);\n        marks.add(80);\n        System.out.println(marks);\n    }\n}\n" }, "App.java", null, "local:java-fixed-size-collection", "new java.util.ArrayList<>(Arrays.asList(70, 65))" },
        { "java", "y1-format-d-for-double", new() { ["App.java"] = "public class App {\n    public static void main(String[] args) {\n        double price = 3.5;\n        System.out.println(String.format(\"Price: %d\", price));\n    }\n}\n" }, "App.java", null, "local:java-format-conversion", "\"Price: %f\"" },
        { "java", "y1-list-of-add", new() { ["App.java"] = "import java.util.List;\n\npublic class App {\n    public static void main(String[] args) {\n        List<String> names = List.of(\"ada\", \"alan\");\n        names.add(\"grace\");\n        System.out.println(names);\n    }\n}\n" }, "App.java", null, "local:java-fixed-size-collection", "new java.util.ArrayList<>(List.of(\"ada\", \"alan\"))" },
        { "java", "y1-main-without-array", new() { ["App.java"] = "public class App {\n    public static void main(String args) {\n        System.out.println(\"hello\");\n    }\n}\n" }, "App.java", null, "local:java-main-signature", "public static void main(String[] args)" },
        { "java", "y2-generic-method-without-type-parameter", new() { ["App.java"] = "import java.util.List;\n\npublic class App {\n    static T first(List<T> items) {\n        return items.get(0);\n    }\n\n    public static void main(String[] args) {\n        System.out.println(first(List.of(\"a\", \"b\")));\n    }\n}\n" }, "App.java", null, "local:java-generic-method-parameter", "static <T> T first(List<T> items)" },
        { "java", "y2-interface-method-with-body", new() { ["App.java"] = "interface Greeter {\n    void greet(String name) {\n        System.out.println(\"Hello, \" + name);\n    }\n}\n\nclass Friendly implements Greeter {\n}\n\npublic class App {\n    public static void main(String[] args) {\n        new Friendly().greet(\"Ada\");\n    }\n}\n" }, "App.java", null, "local:java-interface-default", "default void greet(String name)" },
        { "java", "y2-map-get-increment", new() { ["App.java"] = "import java.util.HashMap;\nimport java.util.Map;\n\npublic class App {\n    public static void main(String[] args) {\n        Map<String, Integer> counts = new HashMap<>();\n        counts.put(\"the\", 0);\n        counts.get(\"the\")++;\n        System.out.println(counts);\n    }\n}\n" }, "App.java", null, "local:java-map-increment", "counts.put(\"the\", counts.get(\"the\") + 1);" },
        { "java", "y2-raw-comparable", new() { ["App.java"] = "import java.util.ArrayList;\nimport java.util.Collections;\nimport java.util.List;\n\nclass Student implements Comparable {\n    String name;\n    int mark;\n\n    Student(String name, int mark) {\n        this.name = name;\n        this.mark = mark;\n    }\n\n    public int compareTo(Student other) {\n        return Integer.compare(mark, other.mark);\n    }\n}\n\npublic class App {\n    public static void main(String[] args) {\n        List<Student> students = new ArrayList<>();\n        students.add(new Student(\"ada\", 90));\n        students.add(new Student(\"alan\", 80));\n        Collections.sort(students);\n        System.out.println(students.get(0).name);\n    }\n}\n" }, "App.java", null, "local:java-raw-comparable", "class Student implements Comparable<Student>" },
        { "java", "y2-raw-comparator", new() { ["App.java"] = "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\nclass Person {\n    String name;\n    int age;\n\n    Person(String name, int age) {\n        this.name = name;\n        this.age = age;\n    }\n}\n\nclass ByAge implements Comparator {\n    public int compare(Person a, Person b) {\n        return Integer.compare(a.age, b.age);\n    }\n}\n\npublic class App {\n    public static void main(String[] args) {\n        List<Person> people = new ArrayList<>();\n        people.add(new Person(\"ada\", 36));\n        people.add(new Person(\"alan\", 41));\n        people.sort(new ByAge());\n        System.out.println(people.get(0).name);\n    }\n}\n" }, "App.java", null, "local:java-raw-comparable", "class ByAge implements Comparator<Person>" },
        { "java", "y2-record-component-as-field", new() { ["App.java"] = "record Point(int x, int y) {\n}\n\npublic class App {\n    public static void main(String[] args) {\n        Point p = new Point(3, 4);\n        System.out.println(p.x + p.y);\n    }\n}\n" }, "App.java", null, "local:java-record-accessor", "p.x() + p.y()" },
        { "java", "y3-future-get-unreported", new() { ["App.java"] = "import java.util.concurrent.CompletableFuture;\n\npublic class App {\n    public static void main(String[] args) {\n        CompletableFuture<Integer> answer = CompletableFuture.supplyAsync(() -> 21 * 2);\n        System.out.println(answer.get());\n    }\n}\n" }, "App.java", null, "local:java-unreported-exception", "throws InterruptedException, java.util.concurrent.ExecutionException" },
        { "java", "y3-not-serializable", new() { ["App.java"] = "import java.io.ByteArrayOutputStream;\nimport java.io.IOException;\nimport java.io.ObjectOutputStream;\n\nclass Student {\n    String name = \"Ada\";\n}\n\npublic class App {\n    public static void main(String[] args) throws IOException {\n        ObjectOutputStream out = new ObjectOutputStream(new ByteArrayOutputStream());\n        out.writeObject(new Student());\n        System.out.println(\"saved\");\n    }\n}\n" }, "App.java", null, "local:java-not-serializable", "class Student implements java.io.Serializable" },
        { "java", "y3-wait-without-synchronized", new() { ["App.java"] = "public class App {\n    private boolean ready = false;\n\n    void waitUntilReady() throws InterruptedException {\n        while (!ready) {\n            wait(100);\n            ready = true;\n        }\n    }\n\n    public static void main(String[] args) throws InterruptedException {\n        new App().waitUntilReady();\n        System.out.println(\"ready\");\n    }\n}\n" }, "App.java", null, "local:java-wait-without-monitor", "synchronized void waitUntilReady()" },
        { "dotnet", "y2-icomparable-not-generic", new() { ["Program.cs"] = "using System;\nusing System.Collections.Generic;\n\nclass Student : IComparable\n{\n    public string Name = \"\";\n    public int Mark;\n\n    public int CompareTo(Student other) => Mark.CompareTo(other.Mark);\n}\n\nclass Program\n{\n    static void Main()\n    {\n        var students = new List<Student> { new Student { Name = \"Ada\", Mark = 90 }, new Student { Name = \"Alan\", Mark = 80 } };\n        students.Sort();\n        Console.WriteLine(students[0].Name);\n    }\n}\n" }, "Program.cs", null, "local:csharp-generic-interface", "class Student : IComparable<Student>" },
        { "dotnet", "y2-record-property-assigned", new() { ["Program.cs"] = "using System;\nusing System.Collections.Generic;\n\nrecord Point(int X, int Y);\n\nclass Program\n{\n    static void Main()\n    {\n        var p = new Point(1, 2);\n        p.X = 5;\n        Console.WriteLine(p);\n    }\n}\n" }, "Program.cs", null, "local:csharp-record-with", "p = p with { X = 5 };" },
        { "dotnet", "y2-struct-in-a-list-changed", new() { ["Program.cs"] = "using System;\nusing System.Collections.Generic;\n\nstruct Point\n{\n    public int X;\n    public int Y;\n}\n\nclass Program\n{\n    static void Main()\n    {\n        var points = new List<Point> { new Point { X = 1, Y = 2 } };\n        points[0].X = 5;\n        Console.WriteLine(points[0].X);\n    }\n}\n" }, "Program.cs", null, "local:csharp-struct-in-collection", "points[0] = point;" },
        { "dotnet", "y2-yield-into-a-list", new() { ["Program.cs"] = "using System;\nusing System.Collections.Generic;\n\nclass Program\n{\n    static List<int> Evens(int limit)\n    {\n        for (int i = 0; i < limit; i += 2)\n            yield return i;\n    }\n\n    static void Main()\n    {\n        foreach (var n in Evens(6))\n            Console.WriteLine(n);\n    }\n}\n" }, "Program.cs", null, "local:csharp-iterator-return-type", "static IEnumerable<int> Evens(int limit)" },
        { "dotnet", "y3-async-void-main", new() { ["Program.cs"] = "using System;\nusing System.Threading.Tasks;\n\nclass Program\n{\n    static async void Main()\n    {\n        await Task.Delay(10);\n        Console.WriteLine(\"done\");\n    }\n}\n" }, "Program.cs", null, "local:csharp-async-main", "static async Task Main()" },
        { "dotnet", "y3-task-not-awaited", new() { ["Program.cs"] = "using System;\nusing System.IO;\nusing System.Threading.Tasks;\n\nclass Program\n{\n    static async Task Main()\n    {\n        await File.WriteAllTextAsync(\"notes.txt\", \"hello\");\n        string text = File.ReadAllTextAsync(\"notes.txt\");\n        Console.WriteLine(text);\n    }\n}\n" }, "Program.cs", null, "local:csharp-task-not-awaited", "string text = await File.ReadAllTextAsync(\"notes.txt\");" },
        { "dotnet", "y3-thread-given-a-call", new() { ["Program.cs"] = "using System;\nusing System.Threading;\n\nclass Program\n{\n    static void Work()\n    {\n        Console.WriteLine(\"working\");\n    }\n\n    static void Main()\n    {\n        var thread = new Thread(Work());\n        thread.Start();\n        thread.Join();\n    }\n}\n" }, "Program.cs", null, "local:csharp-delegate-called", "new Thread(Work)" },
        { "node", "y2-fs-never-required", new() { ["app.js"] = "fs.writeFileSync(\"notes.txt\", \"hello\");\nconsole.log(fs.readFileSync(\"notes.txt\", \"utf8\"));\n" }, "app.js", null, "local:js-builtin-not-loaded", "const fs = require(\"fs\");" },
        { "node", "y2-readfile-without-callback", new() { ["app.js"] = "const fs = require(\"fs\");\n\nfs.writeFileSync(\"notes.txt\", \"hello\");\nconst text = fs.readFile(\"notes.txt\", \"utf8\");\nconsole.log(text.toUpperCase());\n" }, "app.js", null, "local:js-callback-api-used-for-value", "fs.readFileSync(\"notes.txt\", \"utf8\")" },
        { "node", "y2-settimeout-given-a-call", new() { ["app.js"] = "function tick() {\n  console.log(\"tick\");\n}\n\nsetTimeout(tick(), 100);\n" }, "app.js", null, "local:js-callback-called-too-soon", "setTimeout(tick, 100);" },
        { "node", "y3-event-emitter-never-required", new() { ["app.js"] = "class Timer extends EventEmitter {\n  start() {\n    this.emit(\"tick\");\n  }\n}\n\nconst timer = new Timer();\ntimer.on(\"tick\", () => console.log(\"tick\"));\ntimer.start();\n" }, "app.js", null, "local:js-builtin-not-loaded", "const EventEmitter = require(\"events\");" },
        { "node", "y3-promise-all-without-array", new() { ["app.js"] = "const wait = (ms, value) => new Promise((resolve) => setTimeout(() => resolve(value), ms));\n\nasync function main() {\n  const results = await Promise.all(wait(10, \"a\"), wait(20, \"b\"));\n  console.log(results);\n}\n\nmain();\n" }, "app.js", null, "local:js-promise-combinator-array", "Promise.all([wait(10, \"a\"), wait(20, \"b\")])" },
        { "go", "y3-range-over-a-channel-never-closed", new() { ["main.go"] = "package main\n\nimport \"fmt\"\n\nfunc produce(ch chan int) {\n\tfor i := 0; i < 3; i++ {\n\t\tch <- i\n\t}\n}\n\nfunc main() {\n\tch := make(chan int)\n\tgo produce(ch)\n\tfor v := range ch {\n\t\tfmt.Println(v)\n\t}\n}\n" }, "main.go", null, "local:go-close-channel", "\tclose(ch)\n}" },
        { "go", "y3-unmarshal-into-a-value", new() { ["main.go"] = "package main\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n)\n\ntype Config struct {\n\tName string `json:\"name\"`\n}\n\nfunc main() {\n\tvar cfg Config\n\tif err := json.Unmarshal([]byte(`{\"name\":\"ada\"}`), cfg); err != nil {\n\t\tpanic(err)\n\t}\n\tfmt.Println(cfg.Name)\n}\n" }, "main.go", null, "local:go-unmarshal-pointer", "json.Unmarshal([]byte(`{\"name\":\"ada\"}`), &cfg)" },
        { "go", "y3-waitgroup-passed-by-value", new() { ["main.go"] = "package main\n\nimport (\n\t\"fmt\"\n\t\"sync\"\n)\n\nfunc worker(id int, wg sync.WaitGroup) {\n\tdefer wg.Done()\n\tfmt.Println(\"worker\", id)\n}\n\nfunc main() {\n\tvar wg sync.WaitGroup\n\tfor i := 1; i <= 3; i++ {\n\t\twg.Add(1)\n\t\tgo worker(i, wg)\n\t}\n\twg.Wait()\n}\n" }, "main.go", null, "local:go-waitgroup-by-value", "func worker(id int, wg *sync.WaitGroup)" },
        { "c", "y1-scanf-string-ampersand", new() { ["app.c"] = "#include <stdio.h>\n\nint main(void) {\n    char name[20];\n    scanf(\"%19s\", &name);\n    printf(\"Hello, %s\\n\", name);\n    return 0;\n}\n" }, "app.c", "Ada\n", "local:c-scanf-array-address", "scanf(\"%19s\", name);" },
        { "c", "y1-string-compared-with-equals", new() { ["app.c"] = "#include <stdio.h>\n\nint main(void) {\n    char answer[] = \"yes\";\n    if (answer == \"yes\") {\n        printf(\"agreed\\n\");\n    } else {\n        printf(\"not agreed\\n\");\n    }\n    return 0;\n}\n" }, "app.c", null, "local:c-string-compare", "if (strcmp(answer, \"yes\") == 0)" },
        { "c", "y2-grid-rows-sizeof-int", new() { ["app.c"] = "#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int rows = 3, cols = 4;\n    int **grid = malloc(rows * sizeof(int));\n    for (int r = 0; r < rows; r++) {\n        grid[r] = calloc(cols, sizeof(int));\n    }\n    grid[2][3] = 7;\n    printf(\"%d\\n\", grid[2][3]);\n    return 0;\n}\n" }, "app.c", null, "local:c-malloc-wrong-sizeof", "malloc(rows * sizeof *grid)" },
        { "c", "y2-header-without-guard", new() { ["main.c"] = "#include <stdio.h>\n#include \"point.h\"\n#include \"shapes.h\"\n\nint main(void) {\n    struct point p = {1, 2};\n    printf(\"%d\\n\", distance_from_origin(p));\n    return 0;\n}\n", ["point.h"] = "struct point {\n    int x;\n    int y;\n};\n\nstatic const int ORIGIN = 0;\n", ["shapes.c"] = "#include \"shapes.h\"\n\nint distance_from_origin(struct point p) {\n    return p.x + p.y;\n}\n", ["shapes.h"] = "#include \"point.h\"\n\nint distance_from_origin(struct point p);\n" }, "main.c", null, "local:c-header-guard", "#ifndef POINT_H\n#define POINT_H" },
        { "c", "y2-list-freed-while-walked", new() { ["app.c"] = "#include <stdio.h>\n#include <stdlib.h>\n\nstruct node {\n    int value;\n    struct node *next;\n};\n\nint main(void) {\n    struct node *head = NULL;\n    for (int i = 0; i < 3; i++) {\n        struct node *n = malloc(sizeof *n);\n        n->value = i;\n        n->next = head;\n        head = n;\n    }\n    for (struct node *n = head; n != NULL; n = n->next) {\n        free(n);\n    }\n    printf(\"freed\\n\");\n    return 0;\n}\n" }, "app.c", null, "local:c-free-while-walking", "next = n->next;" },
        { "c", "y2-malloc-sizeof-pointer", new() { ["app.c"] = "#include <stdio.h>\n#include <stdlib.h>\n\nstruct node {\n    int value;\n    struct node *next;\n};\n\nint main(void) {\n    struct node *head = malloc(sizeof(struct node *));\n    head->value = 1;\n    head->next = NULL;\n    printf(\"%d\\n\", head->value);\n    free(head);\n    return 0;\n}\n" }, "app.c", null, "local:c-malloc-wrong-sizeof", "malloc(sizeof *head)" },
        { "c", "y2-qsort-comparator-types", new() { ["app.c"] = "#include <stdio.h>\n#include <stdlib.h>\n\nint compare(int *a, int *b) {\n    return *a - *b;\n}\n\nint main(void) {\n    int values[] = {5, 3, 9, 1, 7};\n    qsort(values, 5, sizeof(int), compare);\n    printf(\"%d\\n\", values[0]);\n    return 0;\n}\n" }, "app.c", null, "local:c-qsort-comparator", "int compare(const void *pa, const void *pb)" },
        { "c", "y3-pthread-worker-signature", new() { ["app.c"] = "#include <pthread.h>\n#include <stdio.h>\n\nvoid worker(void *arg) {\n    printf(\"worker %d\\n\", *(int *)arg);\n}\n\nint main(void) {\n    pthread_t thread;\n    int id = 1;\n    pthread_create(&thread, NULL, worker, &id);\n    pthread_join(thread, NULL);\n    return 0;\n}\n" }, "app.c", null, "local:c-pthread-start-routine", "void *worker(void *arg)" },
        { "cpp", "y2-catch-by-value", new() { ["app.cpp"] = "#include <iostream>\n#include <stdexcept>\n\nint main() {\n    try {\n        throw std::runtime_error(\"disk full\");\n    } catch (std::exception e) {\n        std::cout << e.what() << std::endl;\n    }\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-catch-by-reference", "catch (const std::exception& e)" },
        { "cpp", "y2-destructor-not-virtual", new() { ["app.cpp"] = "#include <iostream>\n\nclass Animal {\npublic:\n    ~Animal() { std::cout << \"animal gone\" << std::endl; }\n    virtual void speak() const = 0;\n};\n\nclass Dog : public Animal {\npublic:\n    ~Dog() { std::cout << \"dog gone\" << std::endl; }\n    void speak() const override { std::cout << \"woof\" << std::endl; }\n};\n\nint main() {\n    Animal* pet = new Dog();\n    pet->speak();\n    delete pet;\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-virtual-destructor", "virtual ~Animal()" },
        { "cpp", "y2-index-a-const-map", new() { ["app.cpp"] = "#include <iostream>\n#include <map>\n#include <string>\n\nvoid show(const std::map<std::string, int>& ages) {\n    std::cout << ages[\"ada\"] << std::endl;\n}\n\nint main() {\n    show({{\"ada\", 36}});\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-const-map-index", "ages.at(\"ada\")" },
        { "cpp", "y2-output-operator-as-member", new() { ["app.cpp"] = "#include <iostream>\n\nclass Point {\npublic:\n    int x, y;\n\n    Point(int x, int y) : x(x), y(y) {}\n\n    std::ostream& operator<<(std::ostream& os, const Point& p) {\n        return os << \"(\" << p.x << \", \" << p.y << \")\";\n    }\n};\n\nint main() {\n    std::cout << Point(1, 2) << std::endl;\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-stream-operator-friend", "friend std::ostream& operator<<" },
        { "cpp", "y2-override-missing-const", new() { ["app.cpp"] = "#include <iostream>\n\nclass Shape {\npublic:\n    virtual double area() const = 0;\n    virtual ~Shape() = default;\n};\n\nclass Circle : public Shape {\npublic:\n    double r = 1.0;\n    double area() override { return 3.14159 * r * r; }\n};\n\nint main() {\n    Circle c;\n    std::cout << c.area() << std::endl;\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-override-missing-const", "double area() const override" },
        { "cpp", "y3-thread-reference-argument", new() { ["app.cpp"] = "#include <iostream>\n#include <thread>\n\nvoid increment(int& counter) {\n    ++counter;\n}\n\nint main() {\n    int counter = 0;\n    std::thread worker(increment, counter);\n    worker.join();\n    std::cout << counter << std::endl;\n    return 0;\n}\n" }, "app.cpp", null, "local:cpp-thread-reference", "std::thread worker(increment, std::ref(counter));" },
    };

    [Theory]
    [MemberData(nameof(Programs))]
    public async Task TheMistakeIsFixed(
        string toolchain, string program, Dictionary<string, string> files, string chosen, string? input, string id, string expected)
    {
        if (!LocalFixLiveTests.Available(toolchain)) return;

        using var temp = new TempFolder();

        foreach (var (name, text) in files)
            File.WriteAllText(Path.Combine(temp.Path, name), text);

        var plan = TargetFactory.FromFile(Path.Combine(temp.Path, chosen), TimeSpan.FromMinutes(3));
        Assert.True(plan.Ok, plan.Problem);
        if (input is not null) plan = plan with { Spec = plan.Spec!.WithInput(input) };

        using var http = new FixFinderHttpClient();
        var outcome = await new FixFinderSession(http, new FixSourceRegistry()).RunAsync(plan, new SearchBudget(Cache: CacheMode.CacheOnly));

        Assert.True(outcome.Result == SessionResult.FoundFix, $"{program}: {outcome.Result} - {outcome.Headline}");
        Assert.Equal(id, outcome.Best!.Id);

        var copied = PasteableFix.For(new ExaminedCandidate(outcome.Best, 1, outcome.Candidates.Count, outcome.Harvest, outcome.Plan));

        Assert.NotNull(copied);
        Assert.Contains(expected, copied!.Text.ReplaceLineEndings("\n"), StringComparison.Ordinal);
    }
}
