namespace FixFinder.Core.Execution.BuildFiles;

/// <summary>
/// The programs a Makefile builds, read the way GNU make reads one - its variables, conditionals, includes, rules, pattern
/// rules and the rules make has built in - without running make or anything its recipes would run.
/// </summary>
/// <remarks>
/// A program is a compiler command in a recipe that links rather than only compiles, or a target that make's own rules
/// link. Its sources are the files that command is given; an object file it is given is followed to the rule that makes
/// it, and that rule's command to its source - which is how the flags each source is compiled with are found too. What
/// only running something could say - $(shell ...), a variable the shell sets - is kept as not known rather than taken as
/// empty, and named wherever it matters.
/// </remarks>
internal sealed partial class Makefile
{
    /// <summary>The names GNU make looks for in a folder, in the order it looks.</summary>
    public static readonly IReadOnlyList<string> FileNames = ["GNUmakefile", "makefile", "Makefile"];

    /// <summary>Lines that only a Makefile written by a tool has near its top: CMake's, or automake's and configure's.</summary>
    private static readonly string[] WrittenByATool = ["CMAKE generated file", "Generated by CMake", "generated by automake", "generated automatically by configure"];

    private const int MostFilesIncluded = 20;
    private const int MostEvaluations = 500;

    /// <summary>The folder make runs in - the Makefile's - which every relative name in it is taken from.</summary>
    private readonly string _folder;

    private readonly Dictionary<string, MakeVariable> _variables = new(StringComparer.Ordinal);
    private readonly Dictionary<string, MakeTarget> _targets = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<MakeTarget> _targetsInOrder = [];
    private readonly List<PatternRule> _patternRules = [];
    private readonly List<(string NamePattern, IReadOnlyList<string> Folders)> _searchFolders = [];
    private readonly HashSet<string> _phony = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _suffixes = new(StringComparer.Ordinal) { ".out", ".a", ".o", ".c", ".cc", ".C", ".cpp", ".s", ".S", ".h" };
    private readonly List<string> _filesRead = [];
    private readonly List<string> _notFollowed = [];
    private readonly List<Conditional> _conditionals = [];
    private RecipeOwner? _recipeOwner;
    private string? _firstTarget;
    private int _evaluations;

    private Makefile(string folder)
    {
        _folder = folder;
        _variables["CURDIR"] = new MakeVariable(folder.Replace('\\', '/'), IsSimple: true);
    }

    /// <summary>The files read - the Makefile and those it includes - so a change to any of them is noticed.</summary>
    public IReadOnlyList<string> FilesRead => _filesRead;

    /// <summary>
    /// The Makefile make would read in a folder, unless it was written by a tool rather than a person - named as it is on
    /// disk, since Windows finds Makefile when asked for makefile.
    /// </summary>
    public static string? In(string folder)
    {
        foreach (var name in FileNames)
        {
            string? path;

            try
            {
                path = Directory.EnumerateFiles(folder, name).FirstOrDefault();
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
            {
                return null;
            }

            if (path is null) continue;

            return IsWrittenByATool(path) ? null : path;
        }

        return null;
    }

    public static Makefile Read(string path)
    {
        var full = Path.GetFullPath(path);
        var makefile = new Makefile(Path.GetDirectoryName(full)!);
        makefile.ReadFile(full, depth: 0);
        return makefile;
    }

    private static bool IsWrittenByATool(string path)
    {
        try
        {
            using var reader = new StreamReader(path);
            var start = new char[2048];
            var read = reader.Read(start, 0, start.Length);
            var opening = new string(start, 0, read);

            return WrittenByATool.Any(mark => opening.Contains(mark, StringComparison.OrdinalIgnoreCase));
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return true;
        }
    }

    /// <summary>A variable: its text, and whether that was expanded when it was set (:=) or is expanded each time it is used (=).</summary>
    private sealed record MakeVariable(string Value, bool IsSimple);

    /// <summary>NAME op value, as written - in a Makefile, or for one target (target: NAME op value).</summary>
    private sealed record Assignment(string Name, string Operator, string Value);

    private sealed class MakeTarget(string name)
    {
        public string Name { get; } = name;

        public List<string> Prerequisites { get; } = [];

        public List<string> OrderOnly { get; } = [];

        public List<string>? Recipe { get; set; }

        /// <summary>What % stood for, when a static pattern rule made it: objects: %.o: %.c.</summary>
        public string? Stem { get; set; }

        /// <summary>Values the Makefile gives only this target: app: CFLAGS += -g.</summary>
        public List<Assignment> OwnVariables { get; } = [];
    }

    /// <summary>A rule of the Makefile's own with % in its targets: obj/%.o: src/%.c.</summary>
    private sealed record PatternRule(IReadOnlyList<string> Targets, IReadOnlyList<string> Prerequisites, List<string> Recipe);

    /// <summary>The rule the lines starting with a tab after it belong to.</summary>
    private sealed class RecipeOwner(IReadOnlyList<MakeTarget> targets, PatternRule? pattern)
    {
        private List<string>? _recipe;

        public void Add(string line)
        {
            if (_recipe is null)
            {
                _recipe = pattern?.Recipe ?? [];
                foreach (var target in targets) target.Recipe = _recipe;
            }

            _recipe.Add(line);
        }
    }

    /// <summary>One ifeq ... endif: whether the lines in the part being read count, and whether a part has counted yet.</summary>
    private sealed class Conditional
    {
        public required bool OuterActive { get; init; }

        public bool Active { get; set; }

        public bool Taken { get; set; }
    }

    private bool IsActive => _conditionals.Count == 0 || _conditionals[^1].Active;

    private void ReadFile(string path, int depth)
    {
        string text;

        try
        {
            text = File.ReadAllText(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return;
        }

        _filesRead.Add(path);
        _variables["MAKEFILE_LIST"] = new MakeVariable(string.Join(" ", _filesRead.Select(file => Path.GetRelativePath(_folder, file).Replace('\\', '/'))), IsSimple: true);

        ReadLines(LogicalLines(text), depth);
    }

    /// <summary>The Makefile's lines, with each ending in \ joined to the next as make joins them.</summary>
    private static List<string> LogicalLines(string text)
    {
        var lines = new List<string>();
        var physical = text.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');

        for (var index = 0; index < physical.Length; index++)
        {
            var line = physical[index];
            var isRecipe = line.StartsWith('\t');

            while (EndsWithContinuation(line) && index + 1 < physical.Length)
            {
                var next = physical[++index];
                line = isRecipe
                    ? line[..^1] + (next.StartsWith('\t') ? next[1..] : next)
                    : line[..^1].TrimEnd() + " " + next.TrimStart();
            }

            lines.Add(line);
        }

        return lines;
    }

    private static bool EndsWithContinuation(string line)
    {
        var backslashes = 0;
        for (var at = line.Length - 1; at >= 0 && line[at] == '\\'; at--) backslashes++;

        return backslashes % 2 == 1;
    }

    private void ReadLines(IReadOnlyList<string> lines, int depth)
    {
        var conditionalsBefore = _conditionals.Count;

        for (var index = 0; index < lines.Count; index++)
        {
            var text = lines[index];

            if (text.StartsWith('\t') && _recipeOwner is not null)
            {
                if (IsActive) _recipeOwner.Add(text[1..]);
                continue;
            }

            var line = WithoutComment(text).Trim();
            if (line.Length == 0 || ReadConditional(line)) continue;

            var keyword = FirstWord(line);

            if (!IsActive)
            {
                if (keyword == "define") index = Define(lines, index, line, assign: false);
                continue;
            }

            switch (keyword)
            {
                case "define":
                    index = Define(lines, index, line, assign: true);
                    continue;
                case "include" or "-include" or "sinclude":
                    Include(line[keyword.Length..], depth);
                    _recipeOwner = null;
                    continue;
                case "vpath":
                    SearchFolders(line[keyword.Length..]);
                    continue;
                case "undefine":
                    _variables.Remove(Expand(line[keyword.Length..], Scope.Everywhere).Trim());
                    continue;
            }

            line = WithoutLeadingKeywords(line);
            if (line.Length == 0) continue;

            if (AssignmentIn(line) is { } assignment)
            {
                Assign(assignment, Scope.Everywhere);
                _recipeOwner = null;
                continue;
            }

            if (TopLevelColon(line) >= 0)
            {
                ReadRule(line);
                continue;
            }

            // A line that is only a function: $(eval ...), $(info ...), $(foreach ...) of evals.
            Expand(line, Scope.Everywhere);
        }

        // A file read with an ifeq it never ends is make's error; the lines after it are not left hanging on it.
        if (_conditionals.Count > conditionalsBefore) _conditionals.RemoveRange(conditionalsBefore, _conditionals.Count - conditionalsBefore);
    }

    /// <summary>The line before its first # - which is a comment wherever it is, unless written \#.</summary>
    private static string WithoutComment(string line)
    {
        for (var at = 0; at < line.Length; at++)
        {
            if (line[at] == '\\' && at + 1 < line.Length && line[at + 1] == '#')
            {
                at++;
                continue;
            }

            if (line[at] == '#') return line[..at].Replace("\\#", "#", StringComparison.Ordinal);
        }

        return line.Replace("\\#", "#", StringComparison.Ordinal);
    }

    private static string FirstWord(string line)
    {
        var end = 0;
        while (end < line.Length && !char.IsWhiteSpace(line[end]) && line[end] != '(') end++;

        return line[..end];
    }

    /// <summary>The line without the words that change only how a variable is passed on: override, export, unexport, private.</summary>
    private static string WithoutLeadingKeywords(string line)
    {
        while (FirstWord(line) is "override" or "export" or "unexport" or "private" && (line.Length == FirstWord(line).Length || char.IsWhiteSpace(line[FirstWord(line).Length])))
            line = line[FirstWord(line).Length..].TrimStart();

        return line;
    }

    private bool ReadConditional(string line)
    {
        var keyword = FirstWord(line);
        var rest = line[keyword.Length..].Trim();

        switch (keyword)
        {
            case "ifeq" or "ifneq" or "ifdef" or "ifndef":
            {
                var outerActive = IsActive;
                var holds = outerActive && Holds(keyword, rest);
                _conditionals.Add(new Conditional { OuterActive = outerActive, Active = holds, Taken = holds });
                return true;
            }

            case "else":
            {
                if (_conditionals.Count == 0) return true;

                var current = _conditionals[^1];
                var nested = FirstWord(rest);

                if (nested is "ifeq" or "ifneq" or "ifdef" or "ifndef")
                {
                    var holds = current.OuterActive && !current.Taken && Holds(nested, rest[nested.Length..].Trim());
                    current.Active = holds;
                    current.Taken |= holds;
                }
                else
                {
                    current.Active = current.OuterActive && !current.Taken;
                    current.Taken = true;
                }

                return true;
            }

            case "endif":
                if (_conditionals.Count > 0) _conditionals.RemoveAt(_conditionals.Count - 1);
                return true;

            default:
                return false;
        }
    }

    private bool Holds(string keyword, string condition)
    {
        if (keyword is "ifdef" or "ifndef")
        {
            // ifdef asks whether the variable has a value as written, not whether that value expands to anything.
            var name = Expand(condition, Scope.Everywhere).Trim();
            var defined = UnexpandedValue(name) is { Length: > 0 };

            return keyword == "ifdef" == defined;
        }

        if (Operands(condition) is not { } operands) return false;

        var leftValue = Expand(operands.Left, Scope.Everywhere).Trim();
        var rightValue = Expand(operands.Right, Scope.Everywhere).Trim();

        foreach (var unknown in Unknowable.SourcesIn(leftValue + rightValue))
            NotFollowed($"where it compares {unknown}, it went on as if that gave none of the values compared with it");

        return keyword == "ifeq" == string.Equals(leftValue, rightValue, StringComparison.Ordinal);
    }

    /// <summary>What ifeq compares: (a,b), "a" "b" or 'a' 'b'.</summary>
    private static (string Left, string Right)? Operands(string condition)
    {
        if (condition.StartsWith('('))
        {
            var depth = 0;
            var comma = -1;

            for (var at = 0; at < condition.Length; at++)
            {
                switch (condition[at])
                {
                    case '(' or '{':
                        depth++;
                        break;
                    case ')' or '}':
                        if (--depth == 0 && comma > 0) return (condition[1..comma], condition[(comma + 1)..at]);
                        break;
                    case ',' when depth == 1 && comma < 0:
                        comma = at;
                        break;
                }
            }

            return null;
        }

        if (condition.Length < 2 || condition[0] is not ('"' or '\'')) return null;

        var firstClosing = condition.IndexOf(condition[0], 1);
        if (firstClosing < 0) return null;

        var second = condition[(firstClosing + 1)..].TrimStart();
        if (second.Length < 2 || second[0] is not ('"' or '\'')) return null;

        var secondClosing = second.IndexOf(second[0], 1);
        return secondClosing < 0 ? null : (condition[1..firstClosing], second[1..secondClosing]);
    }

    /// <summary>define NAME ... endef: a variable of several lines, which is how a template for $(eval ...) is written.</summary>
    private int Define(IReadOnlyList<string> lines, int index, string line, bool assign)
    {
        var header = line["define".Length..].Trim();
        var operators = new[] { ":::=", "::=", ":=", "+=", "?=", "!=", "=" };
        var written = operators.FirstOrDefault(op => header.EndsWith(op, StringComparison.Ordinal));
        var name = written is null ? header : header[..^written.Length].Trim();

        var body = new List<string>();
        var nesting = 0;

        for (index++; index < lines.Count; index++)
        {
            var keyword = FirstWord(lines[index].Trim());

            if (keyword == "define") nesting++;
            else if (keyword == "endef" && nesting-- == 0) break;

            body.Add(lines[index]);
        }

        if (assign) Assign(new Assignment(name, written ?? "=", string.Join("\n", body)), Scope.Everywhere);

        _recipeOwner = null;
        return index;
    }

    private void Include(string names, int depth)
    {
        if (depth >= MostFilesIncluded) return;

        foreach (var name in Words(Expand(names, Scope.Everywhere)))
        {
            if (Unknowable.IsIn(name)) continue;

            foreach (var match in PathPattern.HasWildcards(name) ? PathPattern.Matches(_folder, name) : [name])
            {
                var path = Full(match, _folder);
                if (!File.Exists(path) || _filesRead.Contains(path, StringComparer.OrdinalIgnoreCase)) continue;

                var owner = _recipeOwner;
                ReadFile(path, depth + 1);
                _recipeOwner = owner;
            }
        }
    }

    /// <summary>vpath %.c src: the folders a prerequisite matching the pattern is looked for in when it is not where it is named.</summary>
    private void SearchFolders(string text)
    {
        var words = Words(Expand(text, Scope.Everywhere));

        if (words.Count < 2)
        {
            _searchFolders.RemoveAll(entry => words.Count == 0 || entry.NamePattern == words[0]);
            return;
        }

        _searchFolders.Add((words[0], words.Skip(1).SelectMany(word => word.Split(';', StringSplitOptions.RemoveEmptyEntries)).ToList()));
    }

    /// <summary>The assignment the line is, if it is one: the first = or := outside $(...) comes before any colon of a rule.</summary>
    private static Assignment? AssignmentIn(string line)
    {
        var depth = 0;

        for (var at = 0; at < line.Length; at++)
        {
            var character = line[at];

            if (depth > 0)
            {
                if (character is '(' or '{') depth++;
                else if (character is ')' or '}') depth--;
                continue;
            }

            if (character == '$' && at + 1 < line.Length && line[at + 1] is '(' or '{')
            {
                depth++;
                at++;
                continue;
            }

            if (character == '=')
            {
                var operatorStart = at > 0 && line[at - 1] is '?' or '+' or '!' ? at - 1 : at;
                return Assigning(operatorStart, at + 1);
            }

            if (character == ':')
            {
                foreach (var colonOperator in new[] { ":::=", "::=", ":=" })
                {
                    if (string.CompareOrdinal(line, at, colonOperator, 0, colonOperator.Length) == 0) return Assigning(at, at + colonOperator.Length);
                }

                return null;
            }
        }

        return null;

        Assignment? Assigning(int operatorStart, int valueStart)
        {
            var name = line[..operatorStart].Trim();
            return name.Length == 0 || name.Any(char.IsWhiteSpace)
                ? null
                : new Assignment(name, line[operatorStart..valueStart], line[valueStart..].Trim());
        }
    }

    /// <summary>Where the colon of a rule is - outside $(...), and not part of :=.</summary>
    private static int TopLevelColon(string line)
    {
        var depth = 0;

        for (var at = 0; at < line.Length; at++)
        {
            var character = line[at];

            if (character == '$' && at + 1 < line.Length && line[at + 1] is '(' or '{')
            {
                depth++;
                at++;
            }
            else if (depth > 0 && character is '(' or '{') depth++;
            else if (depth > 0 && character is ')' or '}') depth--;
            else if (depth == 0 && character == ':' && (at + 1 == line.Length || line[at + 1] != '=')) return at;
        }

        return -1;
    }

    private static int TopLevelIndexOf(string text, char wanted)
    {
        var depth = 0;

        for (var at = 0; at < text.Length; at++)
        {
            if (text[at] is '(' or '{') depth++;
            else if (text[at] is ')' or '}') depth--;
            else if (depth == 0 && text[at] == wanted) return at;
        }

        return -1;
    }

    private void Assign(Assignment assignment, Scope scope)
    {
        var name = Expand(assignment.Name, scope).Trim();
        if (name.Length == 0 || (assignment.Operator == "?=" && UnexpandedValue(name) is not null)) return;

        _variables[name] = assignment.Operator switch
        {
            ":=" or "::=" or ":::=" => new MakeVariable(Expand(assignment.Value, scope), IsSimple: true),
            "+=" when _variables.TryGetValue(name, out var existing) =>
                existing with { Value = Joined(existing.Value, existing.IsSimple ? Expand(assignment.Value, scope) : assignment.Value) },
            "+=" => new MakeVariable(Joined(UnexpandedValue(name) ?? "", assignment.Value), IsSimple: false),
            "!=" => new MakeVariable(Unknowable.Mark($"{name} != {assignment.Value}"), IsSimple: true),
            _ => new MakeVariable(assignment.Value, IsSimple: false),
        };
    }

    private static string Joined(string first, string second) => first.Length == 0 ? second : second.Length == 0 ? first : $"{first} {second}";

    private void ReadRule(string line)
    {
        var colon = TopLevelColon(line);
        var targetsText = line[..colon];
        var rest = line[(colon + 1)..];
        if (rest.StartsWith(':')) rest = rest[1..];

        string? inlineRecipe = null;
        if (TopLevelIndexOf(rest, ';') is var semicolon and >= 0)
        {
            inlineRecipe = rest[(semicolon + 1)..];
            rest = rest[..semicolon];
        }

        var targetNames = Words(Expand(targetsText, Scope.Everywhere)).Select(Normalised).ToList();

        if (targetNames.Count == 0)
        {
            _recipeOwner = null;
            return;
        }

        // app: CFLAGS += -g gives the variable a value for that target alone, and starts no recipe.
        if (AssignmentIn(rest.Trim()) is { } ownVariable)
        {
            foreach (var targetName in targetNames.Where(written => !written.Contains('%'))) TargetNamed(targetName).OwnVariables.Add(ownVariable);
            _recipeOwner = null;
            return;
        }

        string? staticPattern = null;
        if (TopLevelColon(rest) is var secondColon and >= 0)
        {
            staticPattern = Expand(rest[..secondColon], Scope.Everywhere).Trim();
            rest = rest[(secondColon + 1)..];
        }

        var bar = TopLevelIndexOf(rest, '|');
        var prerequisites = Words(Expand(bar >= 0 ? rest[..bar] : rest, Scope.Everywhere));
        var orderOnly = bar >= 0 ? Words(Expand(rest[(bar + 1)..], Scope.Everywhere)) : [];

        if (targetNames is [var special] && special.StartsWith('.') && !special.Contains('/'))
        {
            _recipeOwner = SpecialTarget(special, prerequisites);
            if (inlineRecipe is not null) _recipeOwner?.Add(inlineRecipe);
            return;
        }

        if (staticPattern is null && targetNames.Any(name => name.Contains('%')))
        {
            var rule = new PatternRule(targetNames, prerequisites, []);
            _patternRules.Add(rule);
            _recipeOwner = new RecipeOwner([], rule);
        }
        else
        {
            var targets = new List<MakeTarget>();

            foreach (var name in targetNames)
            {
                var target = TargetNamed(name);

                if (staticPattern is not null)
                {
                    if (StemOf(staticPattern, name) is not { } stem) continue;

                    target.Stem = stem;
                    target.Prerequisites.AddRange(prerequisites.Select(prerequisite => WithStem(prerequisite, stem)));
                }
                else
                {
                    target.Prerequisites.AddRange(prerequisites);
                }

                target.OrderOnly.AddRange(orderOnly);
                targets.Add(target);
            }

            _firstTarget ??= targetNames.FirstOrDefault(name => !name.StartsWith('.') || name.Contains('/'));
            _recipeOwner = new RecipeOwner(targets, null);
        }

        if (inlineRecipe is not null) _recipeOwner.Add(inlineRecipe);
    }

    /// <summary>
    /// .PHONY names targets that are not files; .SUFFIXES the suffixes old suffix rules use; .c.o: is such a rule, the
    /// same as %.o: %.c. The other special targets change only how make runs, and the recipe after them is not a program's.
    /// </summary>
    private RecipeOwner? SpecialTarget(string name, IReadOnlyList<string> prerequisites)
    {
        switch (name)
        {
            case ".PHONY":
                _phony.UnionWith(prerequisites.Select(Normalised));
                return null;

            case ".SUFFIXES":
                if (prerequisites.Count == 0) _suffixes.Clear();
                else _suffixes.UnionWith(prerequisites);
                return null;
        }

        if (prerequisites.Count == 0 && SuffixRule(name) is { } suffixRule)
        {
            var rule = new PatternRule([$"%{suffixRule.To}"], [$"%{suffixRule.From}"], []);
            _patternRules.Add(rule);
            return new RecipeOwner([], rule);
        }

        return new RecipeOwner([], null);
    }

    /// <summary>.c.o as a suffix rule: from .c to .o. A single suffix, .c, makes a program named like its source.</summary>
    private (string From, string To)? SuffixRule(string name)
    {
        if (_suffixes.Contains(name)) return (name, "");

        for (var split = 1; split < name.Length; split++)
        {
            if (name[split] == '.' && _suffixes.Contains(name[..split]) && _suffixes.Contains(name[split..])) return (name[..split], name[split..]);
        }

        return null;
    }

    private MakeTarget TargetNamed(string name)
    {
        if (_targets.TryGetValue(name, out var target)) return target;

        target = new MakeTarget(name);
        _targets[name] = target;
        _targetsInOrder.Add(target);
        return target;
    }

    /// <summary>A name the way make compares names: / for \, and no ./ in front.</summary>
    private static string Normalised(string name)
    {
        var normalised = name.Replace('\\', '/');
        while (normalised.StartsWith("./", StringComparison.Ordinal) && normalised.Length > 2) normalised = normalised[2..];

        return normalised;
    }

    private void NotFollowed(string what)
    {
        if (!_notFollowed.Contains(what, StringComparer.Ordinal)) _notFollowed.Add(what);
    }

    private static List<string> Words(string text) => text.Split([' ', '\t', '\n', '\r'], StringSplitOptions.RemoveEmptyEntries).ToList();

    private static string Full(string path, string folder)
    {
        try
        {
            return Path.GetFullPath(Path.IsPathRooted(path) ? path : Path.Combine(folder, path));
        }
        catch (Exception ex) when (ex is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return Path.Combine(folder, path);
        }
    }
}
